### ISSUE TITLE
RegExp to specify in plugin settings

### ISSUE THREAD

**Issue by stdword** [YU000jp/logseq-plugin-default-template#4]
Hello! Thanks for a cool plugin! ❤️

There are a set of setting for advanced configuring the page/template binding:
<img width="400px" src="https://github.com/user-attachments/assets/39c9d0fb-9140-4bbe-ace3-58fdbe3e4ba3"/>

But this doesn't cover all cases. For example, I cannot setup template for pages named in the form of Jira tickets (PROJ-123, PROJ-432) or Week pages (2024-W01, 2018-w3).

**Suggestion**: replace all these settings with only one, configuring by regular expressions:
```
PROJ-\d+::jira work template
\d{4}-(w|W)\d\d?::week page template
```

**Comment by YU000jp** [comment]
I will give it a try. It is possible that some users would need a showcase like the one you suggested.
Only a limited number of people can handle regular expressions. I will provide this as a secondary option. The other fields can be left blank.

**Comment by stdword** [comment]
Checked it! Awesome 👍
